name: Latest blog post workflow
on:
  schedule:
    # Fire on Day 1 of every month
    - cron: 0 0 1 * *
  workflow_dispatch:
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://blog.jasonzhuang.com/blog/rss.xml"